// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateAccountResponse struct {
	Success bool `json:"success"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (User) IsEntity() {}
